server:
  port: 9090
spring:
  redis:
    database: 0
    host: localhost
    password:
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0

  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/weixin?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password:
  jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
logging:
  level:
    cn:
      newtol: debug
  path: weiXin
  pattern:
    file: "%d{yyyy-MM-dd} === [%thread] === %-5level === %logger{50} ==== %msg%n"
    console: "%d{yyyy-MM-dd} [%thread] %-5level %logger{50} - %msg%n"

---
# 微信接入部分配置
weiXin:
  # 微信服务器配置的token
  token: bbbbbbbbbb
  # Redis中access_token存储的key
  accessTokenKey: accessToken_
  # 跳转链接的key
  redirectUrlKey: redirect_Url
  # 获取网页授权时，使用的链接地址
  getWebAuthorize: http://newtol.wezoz.com/getWebAuthorize



#  appId: wxc5e0d5b55b141e56
#  appSecret: 782fc50a471b88e87e544885b2dcc782
#  getWebAuthorize: http://ys5p5e.natappfree.cc/getOpenId

# {"url":"http:\/\/mmbiz.qpic.cn\/mmbiz_jpg\/icor8DRGziah4INEIVibGtiapicKQzvibVicNeqwbkUEHefqlNYHeLc94yibH7ZV3FJqdviaZXL0HPUlUvtldfRwnUc2npA\/0"}

# {"media_id":"tP0y34JmbzKUFw-m4Zy6U3VZcoCjUvql9yZfVTa9mwM","url":"http:\/\/mmbiz.qpic.cn\/mmbiz_jpg\/icor8DRGziah4INEIVibGtiapicKQzvibVicNeqwbkUEHefqlNYHeLc94yibH7ZV3FJqdviaZXL0HPUlUvtldfRwnUc2npA\/0?wx_fmt=jpeg"}
# {"media_id":"tP0y34JmbzKUFw-m4Zy6U16PpUXJjo0OP5hxBce3P5s","url":"http:\/\/mmbiz.qpic.cn\/mmbiz_jpg\/icor8DRGziah4INEIVibGtiapicKQzvibVicNeqnvMSEPvK3csvlvKPKaBmwAKMZ9ibUVc9icJXJicNPNM9ViaLrs04YUmJPg\/0?wx_fmt=jpeg"}
menu:
  button:
    - sub_button:
      - clickButton:
        type: click
        name: 点击
        key: hi
      - clickButton:
        type: click
        name: 点击2
        key: hi1
      name: 视图
    - sub_button:
      - clickButton:
        type: view
        name: 视图2
        url: http://newtol.wezoz.com/redirectUrl?state=010e635c254a61fa5af79b246e7b2697
      name: 菜单

